version: 0.2  # Buildspec version used for defining the build pipeline.

phases:
  install:  # Phase for installing dependencies and setting up the environment.
    runtime-versions:  # Define runtime versions for tools used in the build.
      java: corretto17  # Use Amazon Corretto 17 as the Java runtime version.

  build:  #Phase for building the application.
    commands:
      - AWS_REGION="ap-northeast-1"
      - AMI_ID="ami-08c84d37db8aafe00"
      - KEY_PAIR_NAME="HL00886"
      # - java -version  # Print the Java version installed for debugging purposes.
      # - ./mvnw clean package
      # # Execute Maven to clean the project and package the application.
      # # Replace with your desired AWS_REGION, AMI_ID, KEY_PAIR_NAME, SECURITY_GROUP_ID, and SCRIPT_TO_RUN
      # - aws s3api create-bucket --bucket springboot-app-bucket-hello --create-bucket-configuration LocationConstraint=$AWS_REGION
      # - aws s3api put-object --bucket springboot-app-bucket-hello --key spring_boot-0.0.1-SNAPSHOT.war --body target/spring_boot-0.0.1-SNAPSHOT.war
      # - aws cloudformation deploy --template-file ec2.yml --stack-name ec2 --capabilities CAPABILITY_NAMED_IAM --region ap-northeast-1
      - INSTANCE_ID=$(aws cloudformation describe-stacks --stack-name ec2 --query 'Stacks[0].Outputs[*].OutputValue' --output text --region ap-northeast-1)
      - aws ec2 wait instance-running --region $AWS_REGION --instance-ids $INSTANCE_ID
      - IMAGE_ID=$(aws ec2 create-image --instance-id $INSTANCE_ID --name "prj-image" --no-reboot --output text)
      - aws cloudformation delete-stack --stack-name ec2
      #   aws ec2 describe-images --image-ids $IMAGE_ID --region $AWS_REGION

  post_build:  # Phase for post-build actions (optional).
    commands:
      - echo nothing in post build.  # Placeholder command, you can add post-build actions here.

artifacts:  # Configuration for the build output artifacts.
  files: target/spring_boot-0.0.1-SNAPSHOT.war  # The files to be included in the build artifact. In this case, it's the Spring Boot executable WAR file.

