version: 0.2  # Buildspec version used for defining the build pipeline.

phases:
  install:  # Phase for installing dependencies and setting up the environment.
    runtime-versions:  # Define runtime versions for tools used in the build.
      java: corretto17  # Use Amazon Corretto 17 as the Java runtime version.

  build:  # Phase for building the application.
    commands:
      # - java -version  # Print the Java version installed for debugging purposes.
      # - ./mvnw clean package  # Execute Maven to clean the project and package the application.
      # Replace with your desired AWS_REGION, AMI_ID, KEY_PAIR_NAME, SECURITY_GROUP_ID, and SCRIPT_TO_RUN
      - AWS_REGION="ap-northeast-1"
      - AMI_ID="ami-08c84d37db8aafe00"
      - KEY_PAIR_NAME="HL00886"
      - SCRIPT_TO_RUN="path/to/your/script.sh"
      
      # Run the script
      - |
        INSTANCE_ID=$(aws ec2 run-instances \
          --region $AWS_REGION \
          --image-id $AMI_ID \
          --instance-type t2.micro \
          --key-name $KEY_PAIR_NAME \
          --query 'Instances[0].InstanceId' \
          --output text
        )
  post_build:  # Phase for post-build actions (optional).
    commands:
      - echo nothing in post build.  # Placeholder command, you can add post-build actions here.

artifacts:  # Configuration for the build output artifacts.
  files: target/spring_boot-0.0.1-SNAPSHOT.war  # The files to be included in the build artifact. In this case, it's the Spring Boot executable WAR file.

