version: 0.2  # Buildspec version used for defining the build pipeline.

env:
  variables:
    AWS_REGION: "ap-northeast-1"  # Set your desired AWS region here.

phases:
  install:  # Phase for installing dependencies and setting up the environment.
    runtime-versions:  # Define runtime versions for tools used in the build.
      java: corretto17  # Use Amazon Corretto 17 as the Java runtime version.

  build:  # Phase for building the application.
    commands:
      - echo "Building the application..."  # Add any pre-build tasks here.
      - ./build.sh  # Call the build script to build the application.

artifacts:  # Configuration for the build output artifacts.
  files: target/spring_boot-0.0.1-SNAPSHOT.war  # The files to be included in the build artifact. In this case, it's the Spring Boot executable WAR file.
